export const ARXIV_CATEGORIES = {
  cs: {
    name: 'Computer Science',
    categories: {
      'cs.AI': 'Artificial Intelligence',
      'cs.LG': 'Machine Learning',
      'cs.CV': 'Computer Vision and Pattern Recognition',
      'cs.CL': 'Computation and Language',
      'cs.CR': 'Cryptography and Security',
      'cs.DC': 'Distributed, Parallel, and Cluster Computing',
      'cs.DS': 'Data Structures and Algorithms',
      'cs.SE': 'Software Engineering',
      'cs.IT': 'Information Theory',
      'cs.CC': 'Computational Complexity',
      'cs.CG': 'Computational Geometry',
      'cs.GT': 'Computer Science and Game Theory',
      'cs.HC': 'Human-Computer Interaction',
      'cs.IR': 'Information Retrieval',
      'cs.LO': 'Logic in Computer Science',
      'cs.MA': 'Multiagent Systems',
      'cs.MM': 'Multimedia',
      'cs.MS': 'Mathematical Software',
      'cs.NE': 'Neural and Evolutionary Computing',
      'cs.NI': 'Networking and Internet Architecture',
      'cs.OH': 'Other Computer Science',
      'cs.OS': 'Operating Systems',
      'cs.PF': 'Performance',
      'cs.PL': 'Programming Languages',
      'cs.RO': 'Robotics',
      'cs.SC': 'Symbolic Computation',
      'cs.SD': 'Sound',
      'cs.SI': 'Social and Information Networks',
      'cs.SY': 'Systems and Control'
    }
  },
  math: {
    name: 'Mathematics',
    categories: {
      'math.AG': 'Algebraic Geometry',
      'math.AT': 'Algebraic Topology',
      'math.CO': 'Combinatorics',
      'math.DS': 'Dynamical Systems',
      'math.NA': 'Numerical Analysis',
      'math.NT': 'Number Theory',
      'math.PR': 'Probability',
      'math.ST': 'Statistics Theory',
      'math.OC': 'Optimization and Control',
      'math.AC': 'Commutative Algebra',
      'math.AP': 'Analysis of PDEs',
      'math.CA': 'Classical Analysis and ODEs',
      'math.CT': 'Category Theory',
      'math.CV': 'Complex Variables',
      'math.DG': 'Differential Geometry',
      'math.FA': 'Functional Analysis',
      'math.GM': 'General Mathematics',
      'math.GN': 'General Topology',
      'math.GR': 'Group Theory',
      'math.GT': 'Geometric Topology',
      'math.HO': 'History and Overview',
      'math.IT': 'Information Theory',
      'math.KT': 'K-Theory and Homology',
      'math.LO': 'Logic',
      'math.MG': 'Metric Geometry',
      'math.MP': 'Mathematical Physics',
      'math.OA': 'Operator Algebras',
      'math.QA': 'Quantum Algebra',
      'math.RA': 'Rings and Algebras',
      'math.RT': 'Representation Theory',
      'math.SG': 'Symplectic Geometry',
      'math.SP': 'Spectral Theory'
    }
  },
  physics: {
    name: 'Physics',
    categories: {
      'physics.acc-ph': 'Accelerator Physics',
      'physics.ao-ph': 'Atmospheric and Oceanic Physics',
      'physics.atom-ph': 'Atomic Physics',
      'physics.bio-ph': 'Biological Physics',
      'physics.chem-ph': 'Chemical Physics',
      'physics.comp-ph': 'Computational Physics',
      'physics.data-an': 'Data Analysis, Statistics and Probability',
      'physics.flu-dyn': 'Fluid Dynamics',
      'physics.gen-ph': 'General Physics',
      'physics.geo-ph': 'Geophysics',
      'physics.hist-ph': 'History and Philosophy of Physics',
      'physics.ins-det': 'Instrumentation and Detectors',
      'physics.med-ph': 'Medical Physics',
      'physics.optics': 'Optics',
      'physics.plasm-ph': 'Plasma Physics',
      'physics.pop-ph': 'Popular Physics',
      'physics.soc-ph': 'Physics and Society',
      'physics.space-ph': 'Space Physics',
      'physics.class-ph': 'Classical Physics',
      'physics.ed-ph': 'Physics Education'
    }
  }
};
